import json

# List of 100 terms definitions and questions
# Category mapping:
# 1-15: Foundations of Economics & Market Structures
# 16-30: Cost Concepts & Engineering Valuation
# 31-45: Time Value of Money & Interest Concepts
# 46-60: Annuities, Loans & Amortization
# 61-75: Depreciation & Depletion Methods
# 76-90: Capital Budgeting, Feasibility & Evaluation Metrics
# 91-100: Bonds, Inflation, Taxation & Professional Practice

terms = [
    (1, "Scarcity", "Foundations of Economics",
     "What fundamental economic condition forces engineers and decision-makers to evaluate trade-offs and select among competing project alternatives?",
     ["A. Unlimited supply of industrial capital", "B. Unlimited human wants competing for scarce, limited resources", "C. Government regulations on manufacturing tariffs", "D. Currency exchange rate fluctuations"],
     "B", "The universal economic problem of having unlimited human wants in a world of limited resources.",
     "Scarcity mandates that capital, labor, and materials be allocated efficiently through engineering economic analysis.",
     "Scarcity applies to both rich and poor societies; all resources have limits."),

    (2, "Economic Goods vs Free Goods", "Foundations of Economics",
     "Goods that command a positive market price because human effort, labor, or capital is required to produce them are classified as:",
     ["A. Free Goods", "B. Public Goods", "C. Economic Goods", "D. Intangible Goods"],
     "C", "Commodities that are scarce relative to demand and therefore command a market price.",
     "Free goods (like atmospheric air or sea water in nature) are abundant and costless, whereas economic goods require resource expenditure.",
     "A free good becomes an economic good once purified, packaged, or transported (e.g. bottled water)."),

    (3, "Producer (Capital) Goods", "Foundations of Economics",
     "High-voltage power transformers, transmission line conductors, and bucket trucks purchased by an electric utility company are classified as:",
     ["A. Consumer Goods", "B. Producer (Capital) Goods", "C. Giffen Goods", "D. Inferior Goods"],
     "B", "Goods used by businesses and utilities to produce other goods and services rather than for direct consumption.",
     "Producer goods represent investments in productive capacity, depreciated over their economic life.",
     "Consumer goods directly satisfy personal consumer wants (e.g., household lighting)."),

    (4, "Law of Supply and Demand", "Market Mechanisms",
     "According to the classic Law of Demand in competitive markets, how does consumer demand respond when the unit price of a product increases, holding other factors constant?",
     ["A. Quantity demanded increases directly", "B. Quantity demanded decreases inversely", "C. Quantity demanded remains perfectly unchanged", "D. Supply immediately drops to zero"],
     "B", "The economic principle stating that higher prices lead to lower quantity demanded, and vice versa.",
     "The downward slope of the demand curve is caused by substitution effects and income constraints.",
     "A change in price causes a movement along the demand curve, not a shift of the demand curve."),

    (5, "Market Equilibrium Price", "Market Mechanisms",
     "The unique price at which the quantity of an engineering commodity supplied by producers exactly equals the quantity demanded by buyers is known as the:",
     ["A. Ceiling Price", "B. Floor Price", "C. Equilibrium (Market-Clearing) Price", "D. Shadow Price"],
     "C", "The price where market supply equals market demand, clearing the market with neither surplus nor shortage.",
     "At market equilibrium, resources are allocated without administrative rationing.",
     "Price ceilings set below equilibrium create shortages; price floors set above equilibrium create surpluses."),

    (6, "Price Elasticity of Demand", "Market Mechanisms",
     "If an electric cooperative increases residential power rates by 10% and electricity consumption drops by only 2%, the demand for electricity is:",
     ["A. Inelastic (|E_d| < 1)", "B. Unitary Elastic (|E_d| = 1)", "C. Highly Elastic (|E_d| > 1)", "D. Perfectly Elastic (|E_d| = ∞)"],
     "A", "A measure of consumer responsiveness where percentage change in quantity is less than percentage change in price.",
     "|E_d| = 2% / 10% = 0.20 < 1.0, reflecting an essential service with few immediate substitutes.",
     "For inelastic goods, price increases lead to higher total revenues for the supplier."),

    (7, "Law of Diminishing Marginal Utility", "Consumer Theory",
     "The economic principle stating that each additional unit of a good consumed yields progressively less extra satisfaction than the preceding unit is the:",
     ["A. Law of Substitution", "B. Law of Diminishing Marginal Utility", "C. Law of Supply", "D. Law of Comparative Advantage"],
     "B", "As consumption of a commodity increases, the marginal utility derived from each successive unit decreases.",
     "This explains why demand curves slope downward: buyers will only purchase additional units at progressively lower prices.",
     "Total utility may still be increasing as long as marginal utility remains positive."),

    (8, "Law of Diminishing Returns", "Production Economics",
     "When successive units of a variable input (e.g., maintenance crew hours) are applied to a fixed facility (e.g., a power substation), the resulting marginal additions to output will eventually:",
     ["A. Increase exponentially", "B. Decline and decrease", "C. Remain strictly infinite", "D. Fluctuate randomly"],
     "B", "Adding more of one factor of production while holding at least one other factor constant eventually yields lower per-unit incremental returns.",
     "In engineering projects, adding too many workers to a cramped site creates physical bottlenecks and lower productivity.",
     "Total output may continue rising initially, but the marginal product per worker drops."),

    (9, "Pure Monopoly", "Market Structures",
     "A market structure in which a single commercial enterprise has exclusive control over the entire supply of an essential engineering utility service is a:",
     ["A. Monopoly", "B. Monopsony", "C. Oligopoly", "D. Pure Competition"],
     "A", "A market with only one seller facing no direct competitors, protected by substantial barriers to entry.",
     "Electric transmission and distribution utilities are classic natural monopolies regulated by energy regulatory commissions.",
     "A single seller is a monopoly; a single buyer is a monopsony."),

    (10, "Monopsony", "Market Structures",
     "When the Philippine government or a single sovereign grid operator is the sole buyer of specialized high-voltage submarine transmission cables in the country, the market structure is a:",
     ["A. Monopoly", "B. Oligopoly", "C. Monopsony", "D. Duopoly"],
     "C", "A market condition in which there is only one buyer for a product or service offered by multiple suppliers.",
     "A monopsonist has significant leverage to dictate purchasing prices and contract specifications to suppliers.",
     "Do not confuse monopoly (single seller) with monopsony (single buyer)."),

    (11, "Oligopoly", "Market Structures",
     "A market structure dominated by a small handful of large, interdependent firms (such as oil refineries or major telecommunication carriers) is an:",
     ["A. Oligopoly", "B. Perfect Competition", "C. Pure Monopoly", "D. Bilateral Monopoly"],
     "A", "An industry dominated by a small number of sellers who must consider rivals' strategic reactions.",
     "Firms in an oligopoly frequently engage in non-price competition (advertising, service quality) to avoid price wars.",
     "A duopoly is simply an oligopoly with exactly two dominant firms."),

    (12, "Perfect (Pure) Competition", "Market Structures",
     "A theoretical market characterized by a very large number of buyers and sellers, standardized identical products, free entry and exit, and zero market power for individual firms is:",
     ["A. Monopolistic Competition", "B. Perfect Competition", "C. Oligopoly", "D. Regulated Monopoly"],
     "B", "A market structure where individual firms are price takers with zero influence over market price.",
     "In perfect competition, Price = Marginal Revenue = Marginal Cost in long-run equilibrium, and economic profit is zero.",
     "No single firm in perfect competition can set its own price; it takes the market equilibrium price as given."),

    (13, "Monopolistic Competition", "Market Structures",
     "A market containing many sellers offering differentiated products (such as competing electrical engineering consulting firms or power tool brands) is:",
     ["A. Monopolistic Competition", "B. Oligopoly", "C. Pure Monopoly", "D. Perfect Competition"],
     "A", "A market structure combining elements of monopoly (differentiated products) and competition (many sellers with easy entry).",
     "Product branding, professional reputation, and unique features give each firm limited downward-sloping demand.",
     "Unlike pure monopoly, long-run economic profits are eroded by entry of new competitors."),

    (14, "Cartel", "Market Structures",
     "A formal collusive agreement among competing producers in an oligopoly to fix prices, restrict output quotas, and divide market territories (e.g., OPEC) is a:",
     ["A. Cartel", "B. Conglomerate", "C. Joint Venture", "D. Cooperative"],
     "A", "A formal organization of producers that agree to coordinate prices and production to maximize collective profits.",
     "Cartels act like a collective monopoly, but often suffer from internal incentives for individual members to cheat on quotas.",
     "Cartels are illegal under anti-trust and competition laws in most jurisdictions."),

    (15, "Duopoly", "Market Structures",
     "An industry market structure featuring exactly two competing major corporations (such as Airbus and Boeing in large commercial jetliners) is termed a:",
     ["A. Monopoly", "B. Duopoly", "C. Monopsony", "D. Triopoly"],
     "B", "A market structure where exactly two companies control the market for a given product or service.",
     "Classic microeconomic duopoly models include Cournot (quantity competition) and Bertrand (price competition).",
     "A duopoly is a specific subset of an oligopoly."),

    (16, "Sunk Cost", "Cost Concepts",
     "Money that has already been spent on a project in the past and cannot be recovered regardless of any future management decision is called a:",
     ["A. Opportunity Cost", "B. Sunk Cost", "C. Marginal Cost", "D. Working Cost"],
     "B", "A past, historical expenditure that has already occurred and is irrelevant to future economic decisions.",
     "Engineers must ignore sunk costs when evaluating alternatives (e.g., past engineering design fees on an abandoned site).",
     "The 'Sunk Cost Fallacy' is the erroneous desire to continue investing in a failing project simply because much money was already spent."),

    (17, "Opportunity Cost", "Cost Concepts",
     "The monetary value of the next best alternative forgone or sacrificed when choosing a particular engineering investment option is the:",
     ["A. Direct Cost", "B. Overhead Cost", "C. Opportunity Cost", "D. Marginal Cost"],
     "C", "The benefit or return that could have been obtained by choosing the best alternative use of capital.",
     "Opportunity cost establishes the Minimum Attractive Rate of Return (MARR) for capital budgeting.",
     "Opportunity cost does not appear on balance sheets or accounting statements, but is essential for economic decisions."),

    (18, "Marginal Cost", "Cost Concepts",
     "The additional, incremental expenditure required to generate one more unit of an engineered product or service is the:",
     ["A. Average Total Cost", "B. Marginal Cost", "C. Fixed Cost", "D. Sunk Cost"],
     "B", "The change in total cost resulting from producing one additional unit of output: MC = ΔTC / ΔQ.",
     "Profit is maximized at the output level where Marginal Cost (MC) equals Marginal Revenue (MR).",
     "Fixed costs do not affect marginal cost; only variable costs change as output increments."),

    (19, "Fixed Cost", "Cost Concepts",
     "Costs that remain constant in total amount regardless of changes in the volume of goods or services produced over a relevant operating range are:",
     ["A. Fixed Costs", "B. Variable Costs", "C. Marginal Costs", "D. Differential Costs"],
     "A", "Expenses that do not vary with the level of production or sales within a given capacity limit.",
     "Examples include plant building insurance, real estate taxes, executive salaries, and annual software licensing fees.",
     "On a per-unit basis, average fixed cost decreases as production volume increases (economies of scale)."),

    (20, "Variable Cost", "Cost Concepts",
     "Expenses that vary in direct proportion to the volume of output produced, such as raw copper wire, insulating oil, and direct assembly labor, are:",
     ["A. Sunk Costs", "B. Fixed Costs", "C. Variable Costs", "D. Intangible Costs"],
     "C", "Costs that increase or decrease in direct proportion to the volume of units produced.",
     "Total variable cost is calculated as unit variable cost multiplied by quantity: TVC = v × Q.",
     "Variable cost per unit is generally constant, while total variable cost changes with output."),

    (21, "Incremental (Differential) Cost", "Cost Concepts",
     "The difference in total cost between two mutually exclusive engineering design alternatives is referred to as:",
     ["A. Incremental (Differential) Cost", "B. Sunk Cost", "C. Standard Cost", "D. Historical Cost"],
     "A", "The additional cost incurred when choosing one alternative over another.",
     "Used in incremental rate of return (ΔROR) analysis to determine whether extra capital expenditure is economically justified.",
     "Only costs that differ between alternatives are relevant; identical costs cancel out."),

    (22, "Life Cycle Cost (LCC)", "Cost Concepts",
     "The sum of all expenditures associated with an engineering asset from initial conception, design, fabrication, and operation through final disposal is:",
     ["A. First Cost", "B. Life Cycle Cost (LCC)", "C. Book Cost", "D. Prime Cost"],
     "B", "The total cost of ownership throughout the entire operating life of an asset, including acquisition, O&M, and decommissioning.",
     "A piece of equipment with higher initial first cost may have a much lower Life Cycle Cost due to energy efficiency and low maintenance.",
     "Ignoring operating and maintenance costs over the equipment lifespan leads to poor procurement choices."),

    (23, "First Cost (Initial Capital Cost)", "Cost Concepts",
     "The total cash outlay required to develop, purchase, transport, install, and commission an engineering facility ready for operation is the:",
     ["A. First Cost (Capital Cost)", "B. Sunk Cost", "C. Operating Cost", "D. Salvage Cost"],
     "A", "The initial investment required to bring an asset to productive operational status.",
     "First cost includes equipment purchase price, shipping freight, customs duties, foundation construction, and initial testing.",
     "Working capital is typically added to first cost to determine total initial funding required."),

    (24, "Operation and Maintenance (O&M) Cost", "Cost Concepts",
     "Recurring annual expenses necessary to maintain an engineering plant in sound operating condition (e.g., lubricants, inspections, filter changes) are:",
     ["A. First Costs", "B. Capitalized Costs", "C. Operation and Maintenance (O&M) Costs", "D. Sunk Costs"],
     "C", "Ongoing operating expenses needed to maintain functional service throughout equipment life.",
     "O&M costs are usually modeled as uniform annual series (A) or arithmetic gradients (G) in economic studies.",
     "Do not capitalize O&M costs as depreciable assets; they are expensed annually for tax purposes."),

    (25, "Salvage Value vs Scrap Value", "Valuation Concepts",
     "The net cash amount that can be realized from the sale of a used engineering asset at the end of its useful economic life is its:",
     ["A. Salvage Value", "B. Book Value", "C. Par Value", "D. Historical Cost"],
     "A", "The estimated resale or trade-in value of an asset when retired from active service.",
     "Scrap value is the value of the raw materials (metal, copper) if broken up, while salvage value assumes potential utility or resale as equipment.",
     "If removal or demolition costs exceed resale price, net salvage value can be negative."),

    (26, "Book Value", "Accounting & Valuation",
     "The recorded accounting value of an asset on the financial balance sheet, calculated as original first cost minus accumulated depreciation to date, is the:",
     ["A. Market Value", "B. Book Value", "C. Salvage Value", "D. Replacement Value"],
     "B", "The net worth of an asset shown on accounting records: BV = FC - Accumulated Depreciation.",
     "Book value reflects historical cost accounting rules, not necessarily what someone would pay in cash today.",
     "Book value at the end of useful life under standard methods (SLM, SFM) equals salvage value."),

    (27, "Fair Market Value (FMV)", "Accounting & Valuation",
     "The price in cash or equivalent at which a willing buyer and willing seller would freely transact, neither being under compulsion to buy or sell, is:",
     ["A. Fair Market Value", "B. Book Value", "C. Historical Value", "D. Inherent Value"],
     "A", "The estimated price an asset would sell for on the open, competitive market under unforced conditions.",
     "In equipment replacement studies, the defender asset is valued at its current Fair Market Value, not its book value.",
     "Book value is an internal accounting number; market value is an external open-market transaction price."),

    (28, "Replacement Cost", "Valuation Concepts",
     "The estimated cost to build or purchase a modern equivalent facility having identical productive utility to an existing asset is the:",
     ["A. Historical Cost", "B. Sunk Cost", "C. Replacement Cost", "D. Scrap Value"],
     "C", "The current cost of replacing an existing asset with an equally capable modern asset.",
     "Replacement cost reflects current material prices and modern technology, often used in insurance appraisal.",
     "Replacement cost may differ significantly from historical purchase price due to inflation and technological improvements."),

    (29, "Working Capital", "Financial Concepts",
     "The portion of an enterprise's total capital invested in short-term operating assets (cash, inventories of spare parts, accounts receivable) is:",
     ["A. Fixed Capital", "B. Working Capital", "C. Equity Capital", "D. Sunk Capital"],
     "B", "The capital required to finance day-to-day operations: Current Assets minus Current Liabilities.",
     "Working capital is assumed to be fully recovered without depreciation at the conclusion of an engineering project life.",
     "Working capital is NOT depreciated because it consists of liquid operating reserves, not physical plant wear."),

    (30, "Prime Cost vs Conversion Cost", "Cost Accounting",
     "In manufacturing cost accounting, the direct cost of materials plus direct manufacturing labor is known as the:",
     ["A. Conversion Cost", "B. Prime Cost", "C. Overhead Cost", "D. Factory Burden"],
     "B", "The direct production expenditures directly traceable to a manufactured product: Direct Materials + Direct Labor.",
     "Conversion cost is Direct Labor + Factory Overhead (costs to convert raw materials into finished goods).",
     "Direct labor is part of both Prime Cost and Conversion Cost."),

    (31, "Simple Interest (Ordinary vs Exact)", "Interest Theory",
     "Under the standard commercial Banker's Rule in the Philippines, how many days are assumed in a standard year for computing ordinary simple interest?",
     ["A. 360 days", "B. 365 days", "C. 366 days", "D. 365.25 days"],
     "A", "Ordinary simple interest uses 360 days per year (12 months of 30 days each).",
     "Exact simple interest uses 365 days (or 366 in leap years). Ordinary interest yields slightly higher interest earned by the lender.",
     "Unless 'exact' is explicitly specified on PRC board exams, simple interest defaults to Ordinary (360 days)."),

    (32, "Compound Interest", "Interest Theory",
     "The mathematical process wherein interest earned in each period is added to the principal to earn additional interest in subsequent periods is:",
     ["A. Simple Interest", "B. Compound Interest", "C. Amortization", "D. Discounting"],
     "B", "Interest calculated on both initial principal and accumulated interest of prior periods.",
     "Compound interest causes exponential growth of wealth over time: F = P(1 + i)ⁿ.",
     "Simple interest grows linearly; compound interest grows exponentially."),

    (33, "Nominal Interest Rate", "Interest Theory",
     "An annual interest rate that does not account for the compounding effect within the year (e.g., '12% compounded monthly') is a:",
     ["A. Nominal Interest Rate", "B. Effective Annual Rate", "C. Real Interest Rate", "D. Prime Rate"],
     "A", "The stated or contractual annual interest rate r before adjusting for intra-year compounding frequency m.",
     "Periodic rate is calculated as nominal rate divided by compounding periods per year: i = r / m.",
     "A nominal rate cannot be compared directly across different compounding frequencies; convert to Effective Annual Rate first."),

    (34, "Effective Annual Rate (ER)", "Interest Theory",
     "The true annualized interest rate reflecting the full compounding frequency m across a full 12-month calendar year is the:",
     ["A. Nominal Rate", "B. Effective Annual Rate (ER)", "C. Internal Rate of Return", "D. Discount Rate"],
     "B", "The equivalent annual rate accounting for compounding: ER = (1 + r/m)ᵐ - 1.",
     "For m > 1, the Effective Annual Rate is strictly greater than the stated nominal rate.",
     "Compare financing alternatives with differing compounding periods strictly using their Effective Annual Rates."),

    (35, "Continuous Compounding", "Interest Theory",
     "As the compounding frequency m approaches infinity (compounding every infinitesimal fraction of a second), the future worth is governed by:",
     ["A. Euler's constant e: F = P · eʳᵗ", "B. Linear formula: F = P(1 + r·t)", "C. Archimedes constant π: F = P · πʳᵗ", "D. Fibonacci golden ratio φ"],
     "A", "Compounding occurring continuously where lim(1 + r/m)^(mt) as m→∞ equals e^(rt).",
     "Effective annual rate under continuous compounding is ER_cont = eʳ - 1.",
     "Continuous compounding represents the mathematical upper bound on interest accumulation for a given nominal rate."),

    (36, "Rule of 72", "Interest Theory",
     "A convenient mental math rule of thumb to estimate the number of years required for an invested principal to double at annual rate r% is:",
     ["A. Years ≈ 72 / r", "B. Years ≈ 100 / r", "C. Years ≈ 50 · r", "D. Years ≈ r² / 72"],
     "A", "An approximation for doubling time: n ≈ 72 / r, where r is entered as a percentage number (e.g. 6 for 6%).",
     "For continuous compounding, the exact constant is ln(2) ≈ 0.693, making Rule of 69.3 slightly more accurate.",
     "Enter the percentage value (e.g. 8 for 8%), NOT 0.08, when applying the Rule of 72."),

    (37, "Commercial (Bank) Discount Rate", "Interest Theory",
     "A financing method where interest is computed on the maturity value (face value) and deducted in advance from the borrower's loan proceeds is:",
     ["A. Bank (Commercial) Discount", "B. Compound Interest", "C. Ordinary Annuity", "D. Sinking Fund"],
     "A", "Interest charged on the future face value upfront: D = F · d · t; Net Proceeds = F - D.",
     "The borrower receives less than the face value upfront, which raises the effective interest rate above the nominal discount rate.",
     "Relationship between interest rate i and discount rate d: i = d / (1 - d)."),

    (38, "Promissory Note", "Financial Instruments",
     "A formal, unconditional written promise by one party (maker) to pay a specified sum of money to another party (payee) on a fixed future date is a:",
     ["A. Promissory Note", "B. Bill of Lading", "C. Purchase Order", "D. Letter of Credit"],
     "A", "A legal debt instrument containing a written promise to pay a definite sum of money on demand or at maturity.",
     "Maturity value equals face value for non-interest bearing notes; for interest bearing notes, maturity value equals face value plus interest.",
     "Discounting a promissory note before maturity allows the holder to obtain immediate cash from a bank."),

    (39, "Time Value of Money (TVM)", "Foundations of Economics",
     "The fundamental financial premise that a Peso received today is worth more than a Peso to be received in the future is known as the:",
     ["A. Time Value of Money", "B. Purchasing Power Parity", "C. Liquidity Preference", "D. Law of One Price"],
     "A", "The core concept that money available now is worth more than the identical sum later due to its earning potential (interest).",
     "Two cash flows at different points in time cannot be compared directly without discounting or compounding to a common focal date.",
     "Inflation further reinforces TVM, but TVM exists even in an economy with zero inflation due to earning capacity."),

    (40, "Cash Flow Diagram", "Analysis Tools",
     "A graphical representation of cash inflows (plotted upward) and cash outflows (plotted downward) along a horizontal time axis is a:",
     ["A. Gantt Chart", "B. Cash Flow Diagram (CFD)", "C. Pareto Chart", "D. Fishbone Diagram"],
     "B", "A standardized visual tool plotting timing, magnitude, and direction of all project receipts and disbursements.",
     "End-of-period convention is standard in engineering economics: cash flows are assumed to occur at the end of each period.",
     "Upward arrows indicate receipts/inflows (+); downward arrows indicate disbursements/outflows (-)."),

    (41, "End-of-Period Convention", "Analysis Tools",
     "The standard engineering economics convention assuming all cash receipts and disbursements occurring throughout an operating period take place at the:",
     ["A. Beginning of the period", "B. Midpoint of the period", "C. End of the period", "D. Discretion of management"],
     "C", "The simplifying assumption that all cash flows occur instantaneously at the end of the interest period.",
     "Standard compound interest and annuity tables and formulas are derived based on this end-of-period convention.",
     "If payments occur at the beginning of periods, it is an Annuity Due, requiring (1 + i) adjustment."),

    (42, "Ordinary Annuity", "Annuities",
     "A series of uniform, equal cash payments made at equal intervals of time, with payments occurring at the END of each period, is an:",
     ["A. Ordinary Annuity", "B. Annuity Due", "C. Deferred Annuity", "D. Perpetuity"],
     "A", "A uniform series of payments where the first payment occurs one period after time zero.",
     "Present worth: P = A[(1 - (1 + i)⁻ⁿ) / i]; Future worth: F = A[((1 + i)ⁿ - 1) / i].",
     "Car loans and mortgages standardly operate as ordinary annuities with payments at the end of each month."),

    (43, "Annuity Due", "Annuities",
     "An equal payment series in which periodic installments are paid at the BEGINNING of each compounding period (e.g., advance equipment lease rentals) is an:",
     ["A. Ordinary Annuity", "B. Annuity Due", "C. Sinking Fund", "D. Perpetuity"],
     "B", "A uniform series where each payment occurs at the start of each period, starting at time zero.",
     "Present value relationship: P_due = P_ordinary · (1 + i); Future value: F_due = F_ordinary · (1 + i).",
     "Because money is paid one period earlier, each payment earns interest for one additional compounding period."),

    (44, "Deferred Annuity", "Annuities",
     "An annuity in which the first periodic payment is postponed or delayed for a specified grace period of m intervals is a:",
     ["A. Deferred Annuity", "B. Immediate Annuity", "C. Perpetuity", "D. Amortization"],
     "A", "An annuity where payments begin after a postponement or grace period: P_def = P_ordinary · (1 + i)⁻ᵐ.",
     "If first payment occurs at the end of period k, the deferred periods are m = k - 1.",
     "Do not set m = k; remember that an ordinary annuity's first payment normally occurs at the end of period 1."),

    (45, "Perpetuity", "Annuities",
     "An equal payment series that continues indefinitely into the future with no termination date (n → ∞) is termed a:",
     ["A. Term Annuity", "B. Perpetuity", "C. Sinking Fund", "D. Sunk Asset"],
     "B", "An infinite uniform cash flow series with present value: P = A / i.",
     "Examples include endowment funds, perpetual scholarship trusts, and government perpetual consolidated bonds (consols).",
     "As n approaches infinity, the factor (1 + i)⁻ⁿ approaches zero, simplifying P = A / i."),

    (46, "Capitalized Cost", "Capitalized Cost",
     "The single present lump-sum endowment required to construct, operate, maintain, and replace an engineering facility indefinitely into perpetuity is the:",
     ["A. Salvage Value", "B. Capitalized Cost", "C. Sunk Cost", "D. Book Cost"],
     "B", "The present worth of an engineering asset having infinite service life: CC = FC + (OM / i) + [RC / ((1 + i)ᵏ - 1)].",
     "Widely used for comparing permanent infrastructure like suspension bridges, dams, irrigation channels, and highway tunnels.",
     "The periodic renewal term has denominator ((1 + i)ᵏ - 1); do not divide by i for periodic renewals."),

    (47, "Sinking Fund Factor", "Annuity Factors",
     "The mathematical factor [i / ((1 + i)ⁿ - 1)] used to compute the required uniform periodic deposit A to accumulate a future lump sum F is the:",
     ["A. Capital Recovery Factor", "B. Sinking Fund Factor (A/F)", "C. Present Worth Factor", "D. Gradient Factor"],
     "B", "The factor determining periodic savings needed to reach a targeted future balance: A = F · (A/F, i, n).",
     "Commonly used to accumulate funds for future bond redemption or major plant equipment replacements.",
     "Sinking fund solves for A given F; Capital recovery solves for A given present principal P."),

    (48, "Capital Recovery Factor", "Annuity Factors",
     "The mathematical factor [i(1 + i)ⁿ / ((1 + i)ⁿ - 1)] used to calculate the uniform periodic payment A required to amortize a present loan principal P is the:",
     ["A. Capital Recovery Factor (A/P)", "B. Sinking Fund Factor", "C. Compound Amount Factor", "D. Gradient Series Factor"],
     "A", "The factor calculating the periodic payment that amortizes a present loan with interest: A = P · (A/P, i, n).",
     "Capital recovery factor equals Sinking Fund Factor plus interest rate: (A/P) = (A/F) + i.",
     "Standardly used for calculating equal monthly mortgage or equipment installment payments."),

    (49, "Arithmetic Gradient Series", "Gradient Factors",
     "A cash flow sequence that increases or decreases by a constant arithmetic dollar increment G each successive period is an:",
     ["A. Arithmetic Gradient Series", "B. Geometric Gradient Series", "C. Ordinary Annuity", "D. Perpetuity"],
     "A", "Cash flows where CF_t = A₁ + (t - 1)·G for t = 1, 2, ... n.",
     "Converted to an equivalent uniform annual series using factor: (A/G, i, n) = 1/i - n/((1 + i)ⁿ - 1).",
     "The gradient G begins with zero increment in period 1; the first increase G occurs in period 2."),

    (50, "Geometric Gradient Series", "Gradient Factors",
     "A cash flow sequence that increases or decreases by a constant percentage compounding rate g each period (e.g. inflation escalation) is a:",
     ["A. Arithmetic Gradient Series", "B. Geometric Gradient Series", "C. Linear Series", "D. Amortization"],
     "B", "Cash flows growing at a constant percentage rate g: CF_t = A₁ · (1 + g)ᵗ⁻¹.",
     "Used to model energy fuel cost escalation, inflation-adjusted maintenance contracts, and wage increases.",
     "When g = i, the present worth formula simplifies to P = n · A₁ / (1 + i)."),

    (51, "Loan Amortization", "Loan Management",
     "The systematic process of gradually extinguishing a debt obligation over time through scheduled periodic payments of principal and interest is:",
     ["A. Capitalization", "B. Amortization", "C. Depletion", "D. Compounding"],
     "B", "Retiring a debt in installments, where each payment covers accrued interest and reduces the principal.",
     "In an amortization schedule, the interest portion decreases over time while the principal portion increases.",
     "Outstanding balance at payment k equals the present value of all remaining future payments."),

    (52, "Balloon Payment", "Loan Management",
     "A disproportionately large final payment scheduled at the end of a loan term to pay off the remaining unamortized principal balance is a:",
     ["A. Sunk Payment", "B. Balloon Payment", "C. Annuity Due", "D. Grace Payment"],
     "B", "A lump-sum final payment due at maturity that is substantially larger than regular periodic installments.",
     "Often used when borrowers expect future refinancing or capital inflows before maturity.",
     "Borrowers face refinancing risk if unable to secure new financing when the balloon payment comes due."),

    (53, "Depreciation (Accounting Definition)", "Depreciation Theory",
     "The systematic allocation of the depreciable cost of a physical engineering asset over its estimated useful economic life is:",
     ["A. Amortization", "B. Depreciation", "C. Depletion", "D. Devaluation"],
     "B", "An accounting process of allocating asset cost to expense over the periods benefited by its use.",
     "Depreciation is a non-cash expense that reduces taxable income, creating cash tax shield savings.",
     "Land does not depreciate under tax laws because its useful life is considered indefinite."),

    (54, "Physical vs Functional Depreciation", "Depreciation Theory",
     "Depreciation caused by technological obsolescence, superceded designs, or inadequacy rather than physical wear and tear is termed:",
     ["A. Physical Depreciation", "B. Functional (Obsolescence) Depreciation", "C. Accidental Depreciation", "D. Depletion"],
     "B", "Loss in economic value due to technological advancement, changes in demand, or inadequacy.",
     "Physical depreciation results from friction, rust, corrosion, and thermal wear; functional depreciation results from superior new models.",
     "An electrical device may be in pristine physical condition yet functionally obsolete due to digital standards."),

    (55, "Straight-Line Depreciation (SLM)", "Depreciation Methods",
     "The depreciation method that allocates an identical, uniform amount of depreciation expense to every year of an asset's useful life is:",
     ["A. Straight-Line Method (SLM)", "B. Sinking Fund Method", "C. Declining Balance Method", "D. Sum-of-the-Years-Digits"],
     "A", "The simplest depreciation method with constant annual charge: d = (FC - SV) / n.",
     "Book value declines linearly from initial first cost FC down to salvage value SV at year n.",
     "Most widely used method in financial reporting due to simplicity and predictability."),

    (56, "Sinking Fund Depreciation (SFM)", "Depreciation Methods",
     "The depreciation method that assumes an imaginary sinking fund earning compound interest accumulates the reserve required to replace the asset is:",
     ["A. Straight-Line Method", "B. Sinking Fund Method (SFM)", "C. Matheson Method", "D. Double Declining Method"],
     "B", "A method where annual depreciation increases each year as compound interest accrues on the accumulated reserve.",
     "Annual basic deposit is d = (FC - SV)[i / ((1 + i)ⁿ - 1)]; total annual charge in year m is basic deposit plus interest on reserve.",
     "Because interest grows, annual depreciation increases over time, the opposite of accelerated methods."),

    (57, "Sum-of-the-Years-Digits (SOYD)", "Depreciation Methods",
     "An accelerated depreciation method applying a decreasing fraction (remaining life over the sum of digits Σ) to the total depreciable base is:",
     ["A. SOYD Method", "B. SLM Method", "C. Sinking Fund Method", "D. Production Units Method"],
     "A", "An accelerated method where annual depreciation is d_m = (FC - SV) · (n - m + 1) / Σ, with Σ = n(n + 1)/2.",
     "Depreciation is highest in Year 1 and decreases by a constant arithmetic amount every year.",
     "On Canon F-789SGA, compute sum of digits Σ using [SHIFT] [log] (Σ) from 1 to n."),

    (58, "Declining Balance Method (Matheson / DBM)", "Depreciation Methods",
     "An accelerated depreciation method that applies a constant fixed percentage rate k = 1 - (SV/FC)^(1/n) to the declining book value of each year is:",
     ["A. Straight-Line Method", "B. Declining Balance Method (DBM / Matheson)", "C. Sinking Fund Method", "D. Service Output Method"],
     "B", "An accelerated method with constant rate k: d_m = k · BV_{m-1}, BV_m = FC(1 - k)ᵐ.",
     "Salvage value SV must be strictly greater than zero; if SV = 0, rate k would mathematically equal 100%.",
     "Book value never reaches zero; it asymptotically approaches salvage value."),

    (59, "Double Declining Balance Method (DDBM)", "Depreciation Methods",
     "An accelerated tax depreciation method using twice the straight-line rate (k = 2 / n) applied to remaining book value, initially ignoring salvage value, is:",
     ["A. SOYD", "B. Double Declining Balance (DDBM)", "C. Sinking Fund Method", "D. Unit of Production Method"],
     "B", "A declining balance method using fixed rate k = 2 / n without subtracting SV in the rate formula.",
     "Depreciation stops when book value drops to the salvage value floor; an asset is not depreciated below SV.",
     "Yields very large tax deductions in early years, conserving cash flow for growing enterprises."),

    (60, "Service Output (Production Units) Depreciation", "Depreciation Methods",
     "A depreciation method that allocates equipment wear based on the total units of physical output produced (e.g. kilowatt-hours generated) is the:",
     ["A. Straight-Line Method", "B. Service Output (Production Units) Method", "C. Matheson Method", "D. SOYD Method"],
     "B", "Depreciation per unit = (FC - SV) / Total Rated Output; Annual charge = Units produced × Unit rate.",
     "Appropriate when equipment deterioration is directly tied to usage intensity rather than passage of time.",
     "Similar to the working hours method, substituting machine hours with units produced."),

    (61, "Working Hours Depreciation", "Depreciation Methods",
     "A depreciation method where the depreciation cost is allocated based on machine operating hours logged during the year is the:",
     ["A. Working Hours Method", "B. Straight-Line Method", "C. Sinking Fund Method", "D. Sum of Digits Method"],
     "A", "Hourly rate = (FC - SV) / Total Operating Hours; Annual depreciation = Hours logged × Hourly rate.",
     "Heavily used for aircraft engines, industrial turbines, and standby diesel generator sets.",
     "Years with heavy operational running log higher depreciation, matching revenues with expenses."),

    (62, "Depletion (Cost vs Percentage)", "Resource Accounting",
     "The physical exhaustion of natural mineral deposits, oil wells, or timber stands through extraction is accounted for as:",
     ["A. Depreciation", "B. Amortization", "C. Depletion", "D. Devaluation"],
     "C", "The accounting allocation of the cost of extracting natural resources from the earth.",
     "Cost depletion is based on actual extracted volume / total reserves; Percentage depletion is a statutory % of gross income.",
     "Depreciation applies to man-made assets; depletion applies to natural resources that cannot be rebuilt."),

    (63, "Minimum Attractive Rate of Return (MARR)", "Evaluation Criteria",
     "The lowest hurdle rate of return acceptable to an enterprise before committing capital to an engineering project is the:",
     ["A. Internal Rate of Return", "B. Minimum Attractive Rate of Return (MARR / Hurdle Rate)", "C. Prime Lending Rate", "D. Coupon Rate"],
     "B", "The cut-off discount rate reflecting corporate cost of capital plus risk premium.",
     "Projects yielding returns below MARR are rejected because capital could earn more elsewhere.",
     "MARR is established by corporate management, not calculated from the project's own cash flows."),

    (64, "Internal Rate of Return (IRR)", "Evaluation Criteria",
     "The specific discount rate that makes the Net Present Value (NPV) of all project cash inflows and outflows exactly equal to zero is the:",
     ["A. MARR", "B. Internal Rate of Return (IRR)", "C. External Rate of Return", "D. Inflation Rate"],
     "B", "The interest rate generated internally by an investment: NPV(IRR) = 0.",
     "An independent project is economically acceptable if its IRR is strictly greater than or equal to MARR.",
     "Solving for IRR generally requires trial-and-error interpolation or calculator [SOLVE]."),

    (65, "Incremental Rate of Return (ΔROR)", "Evaluation Criteria",
     "When selecting between mutually exclusive alternatives of differing initial investments, the rate of return earned on the extra capital expenditure is:",
     ["A. Simple IRR", "B. Incremental Rate of Return (ΔROR)", "C. External ROR", "D. Sunk Rate"],
     "B", "The rate of return calculated on the incremental cash flows between higher-cost and lower-cost alternatives.",
     "The higher-investment alternative is justified only if the incremental return ΔROR ≥ MARR.",
     "Picking the project with the highest standalone IRR can lead to incorrect decisions for mutually exclusive options; use ΔROR!"),

    (66, "Net Present Value (NPV / Present Worth Method)", "Evaluation Criteria",
     "The sum of all discounted cash inflows minus the sum of all discounted cash outflows evaluated at the corporate MARR is the:",
     ["A. Net Present Value (NPV / PW)", "B. Future Worth", "C. Payback Period", "D. Sunk Capital"],
     "A", "The net economic surplus created by a project in today's Pesos discounted at MARR.",
     "Decision rule: Accept independent projects if NPV ≥ 0; for mutually exclusive choices, select the alternative with the highest positive NPV.",
     "NPV assumes cash inflows can be reinvested at the MARR rate."),

    (67, "Annual Worth Method (EUAC / EUAW)", "Evaluation Criteria",
     "Converting all project cash flows into an equivalent uniform annual series of equal payments over the asset life is the:",
     ["A. Annual Worth Method (Equivalent Uniform Annual Worth / Cost)", "B. Payback Method", "C. Sunk Cost Method", "D. Internal Rate Method"],
     "A", "The uniform annual equivalent of all receipts and disbursements: AW = PW · (A/P, i, n).",
     "Especially powerful when comparing mutually exclusive alternatives with UNEQUAL useful lifespans.",
     "Under the repeatability assumption, alternatives with unequal lives can be compared directly via AW without least common multiple (LCM)."),

    (68, "Benefit-Cost Ratio (B/C)", "Evaluation Criteria",
     "In public infrastructure projects (flood control, rural electrification), the ratio of present worth of public benefits to present worth of government costs is:",
     ["A. Benefit-Cost Ratio (B/C)", "B. Profitability Ratio", "C. Debt-to-Equity Ratio", "D. Current Ratio"],
     "A", "A project feasibility criterion: B/C = PW(Benefits) / PW(Costs). Project is economically justified if B/C ≥ 1.0.",
     "Disbenefits (adverse effects to public) are subtracted from benefits in the numerator.",
     "For mutually exclusive public projects, incremental benefit-cost analysis (ΔB/ΔC ≥ 1.0) must be used."),

    (69, "Modified Benefit-Cost Ratio", "Evaluation Criteria",
     "A variation of the B/C ratio where annual operation and maintenance (O&M) expenses are subtracted from benefits in the numerator rather than added to costs in the denominator is:",
     ["A. Conventional B/C Ratio", "B. Modified Benefit-Cost Ratio (B/C_mod)", "C. Internal B/C Ratio", "D. Net Benefit Index"],
     "B", "B/C_mod = [PW(Benefits) - PW(O&M)] / Initial Investment.",
     "Both conventional and modified B/C ratios yield the identical accept/reject decision (≥ 1.0), but slightly different numerical values.",
     "The denominator in modified B/C contains strictly initial capital investments."),

    (70, "Simple Payback Period", "Evaluation Criteria",
     "The length of time required for the undiscounted cumulative operating cash inflows to equal the initial capital investment is the:",
     ["A. Simple Payback Period", "B. Discounted Payback Period", "C. Break-Even Period", "D. Operating Cycle"],
     "A", "The number of years to recover first cost without interest: Payback = FC / Annual Cash Flow.",
     "Measures liquidity and capital recovery speed, but ignores time value of money and cash flows occurring after payback.",
     "Never use simple payback as the primary criterion for long-term project selection; it ignores life-cycle returns."),

    (71, "Discounted Payback Period", "Evaluation Criteria",
     "The time required for cumulative discounted cash inflows (at the corporate MARR) to recover the initial capital investment is the:",
     ["A. Simple Payback Period", "B. Discounted Payback Period", "C. Capital Recovery Period", "D. Salvage Period"],
     "B", "The number of periods required for discounted revenues to offset initial investment.",
     "Always strictly longer than simple payback because discounting reduces the present value of future cash inflows.",
     "Accounts for time value of money, but still ignores cash flows generated beyond the payback date."),

    (72, "Break-Even Point (BEP)", "Break-Even Analysis",
     "The operating production volume at which total operating revenues exactly equal total operating costs, resulting in zero profit and zero loss, is the:",
     ["A. Shut-Down Point", "B. Break-Even Point (BEP)", "C. Saturation Point", "D. Equilibrium Volume"],
     "B", "Output level where Total Revenue = Total Cost: Q_BEP = FC / (p - v).",
     "Below the break-even volume, the enterprise incurs an operating loss; above it, it realizes operating profits.",
     "Break-even sales in Pesos = Q_BEP × Price = FC / [1 - (v / p)]."),

    (73, "Contribution Margin (CM)", "Break-Even Analysis",
     "The portion of sales revenue remaining after deducting all variable costs, which goes toward covering fixed overhead and generating profit, is:",
     ["A. Gross Margin", "B. Contribution Margin (CM)", "C. Net Margin", "D. Operating Margin"],
     "B", "Unit CM = Price - Variable Cost (p - v); Contribution Margin Ratio = (p - v) / p.",
     "Each additional unit sold contributes (p - v) Pesos toward paying off fixed costs.",
     "Once fixed costs are fully covered, 100% of additional contribution margin flows directly into net profit."),

    (74, "Margin of Safety (MOS)", "Break-Even Analysis",
     "The amount or percentage by which expected sales volume exceeds the break-even volume, representing the cushion against operating losses, is:",
     ["A. Operating Leverage", "B. Margin of Safety (MOS)", "C. Safety Stock", "D. Reserve Margin"],
     "B", "MOS = (Current Sales - Break-Even Sales) / Current Sales × 100%.",
     "A higher margin of safety indicates lower financial risk and greater buffer against market downturns.",
     "An enterprise operating exactly at break-even has an MOS of 0%."),

    (75, "Shut-Down Point (Cash Break-Even)", "Break-Even Analysis",
     "The minimum operating output level below which an industrial plant should temporarily shut down because revenue fails to cover even variable operating cash costs is the:",
     ["A. Accounting Break-Even", "B. Shut-Down Point", "C. Expansion Point", "D. Maximum Capacity"],
     "B", "The point where Price equals Average Variable Cost (p = AVC), or Cash Revenue equals Cash Variable Costs.",
     "In the short run, a firm will continue operating at a loss as long as revenue covers variable costs and contributes something toward fixed costs.",
     "If price drops below unit variable cost, every unit produced increases total losses."),

    (76, "Capital Rationing", "Capital Budgeting",
     "The management constraint where an enterprise has more viable positive-NPV projects than it has available capital budget to fund them is:",
     ["A. Capital Rationing", "B. Dilution of Equity", "C. Capital Deepening", "D. Liquidity Squeeze"],
     "A", "A situation where a fixed financial ceiling limits the total capital expenditures a company can undertake in a given year.",
     "Projects must be ranked by Profitability Index (PI) or combined in integer programming packages to maximize total portfolio NPV.",
     "Under capital rationing, simply picking projects by standalone IRR can leave capital unspent with suboptimal total NPV."),

    (77, "Profitability Index (Benefit-to-Cost Index)", "Capital Budgeting",
     "The ratio of the present worth of future net cash inflows to the initial capital outlay of an investment is the:",
     ["A. Profitability Index (PI)", "B. Current Ratio", "C. Quick Ratio", "D. Payback Ratio"],
     "A", "PI = PW(Cash Inflows) / Initial Investment. Acceptable if PI ≥ 1.0.",
     "Useful for ranking projects of differing sizes under capital rationing constraints.",
     "PI is mathematically equivalent to the Benefit-Cost ratio applied to private commercial investments."),

    (78, "Mutually Exclusive Alternatives", "Capital Budgeting",
     "A set of engineering project proposals where selecting one alternative automatically and totally precludes the selection of any of the others is:",
     ["A. Independent Projects", "B. Mutually Exclusive Alternatives", "C. Contingent Projects", "D. Complementary Projects"],
     "B", "Proposals that accomplish the identical objective such that only one can be chosen (e.g. diesel generator vs solar PV system).",
     "When evaluating mutually exclusive alternatives, select the single option with the maximum Net Present Value.",
     "Independent projects can all be accepted simultaneously as long as they meet MARR and budget permits."),

    (79, "Sensitivity Analysis", "Risk & Uncertainty",
     "An engineering economic technique that tests how changes in uncertain parameter estimates (e.g., fuel price, power tariffs, equipment life) affect the project NPV is:",
     ["A. Sensitivity Analysis", "B. Sunk Cost Analysis", "C. Break-Even Balancing", "D. Regression Analysis"],
     "A", "Varying key project parameters one at a time across a range of percentage deviations to observe impact on profitability.",
     "Visualized through 'Spider Plots' where steeper slopes indicate parameters to which the project is most sensitive and vulnerable.",
     "Helps engineers identify critical risk variables that require hedging, insurance, or rigorous monitoring."),

    (80, "Bond", "Financial Instruments",
     "A long-term debt security issued by a government or corporation promising to pay periodic coupon interest plus the par face value at maturity is a:",
     ["A. Common Stock", "B. Bond", "C. Preferred Stock", "D. Warrant"],
     "B", "A debt obligation where the issuer borrows funds and agrees to pay coupon dividends and redemption value at maturity.",
     "Bond valuation formula: P = C(1 + i)⁻ⁿ + Fr[(1 - (1 + i)⁻ⁿ) / i].",
     "Bondholders are creditors with prior claim over equity shareholders during corporate liquidation."),

    (81, "Bond Coupon Rate vs Yield to Maturity", "Financial Instruments",
     "The contractual interest rate stated on the face of a bond that determines the periodic cash dividend payment is the:",
     ["A. Yield to Maturity (Market Yield)", "B. Coupon Rate", "C. Prime Rate", "D. Discount Rate"],
     "B", "The stated interest rate r printed on the bond certificate that determines periodic coupon payment: Periodic Coupon = F · r.",
     "Yield to maturity (i) is the prevailing market interest rate required by investors based on current economic conditions.",
     "If Market Yield > Coupon Rate, the bond trades at a DISCOUNT; if Market Yield < Coupon Rate, it trades at a PREMIUM."),

    (82, "Premium Bond vs Discount Bond", "Financial Instruments",
     "When a bond's purchase price in the secondary market is lower than its face par value because market interest rates have risen above its coupon rate, it is a:",
     ["A. Premium Bond", "B. Discount Bond", "C. Par Bond", "D. Zero-Coupon Bond"],
     "B", "A bond selling below its face value (P < F) because its coupon yield is lower than current market rates.",
     "A bond selling above face value (P > F) is a premium bond.",
     "At maturity date, the market value of all bonds converges exactly to the par redemption value."),

    (83, "Current Yield of a Bond", "Financial Instruments",
     "The ratio of a bond's annual coupon dividend payment to its current market purchase price is the:",
     ["A. Yield to Maturity", "B. Current Yield", "C. Coupon Rate", "D. Nominal Yield"],
     "B", "Current Yield = Annual Coupon Payment / Current Market Price.",
     "Current yield measures annual cash income return, but ignores capital gains or losses realized at redemption.",
     "Yield to maturity is a more comprehensive metric than current yield because it accounts for redemption value."),

    (84, "Inflation", "Macroeconomic Concepts",
     "A general and sustained increase in the overall price level of goods and services in an economy, causing a decline in the purchasing power of money, is:",
     ["A. Inflation", "B. Deflation", "C. Stagflation", "D. Recession"],
     "A", "The erosion of purchasing power where a fixed sum of currency buys fewer physical goods over time.",
     "Measured by the percentage increase in consumer price index (CPI): Future Cost = Present Cost · (1 + f)ⁿ.",
     "Deflation is the opposite condition: a persistent decrease in the general price level."),

    (85, "Fisher Relation (Real vs Nominal Interest Rate)", "Macroeconomic Concepts",
     "The classical financial equation relating nominal interest rate d, real interest rate i_real, and inflation rate f is:",
     ["A. (1 + d) = (1 + i_real)(1 + f)", "B. d = i_real · f", "C. (1 + d) = (1 + i_real) / (1 + f)", "D. d = i_real - f"],
     "A", "Fisher Equation: (1 + d) = (1 + i_real)(1 + f), which expands to d = i_real + f + (i_real · f).",
     "Solving for real interest rate: i_real = [(1 + d) / (1 + f)] - 1.",
     "The common approximation d ≈ i_real + f overstates real return; on PRC board exams, always use the exact formula."),

    (86, "Constant Pesos vs Current (Actual) Pesos", "Macroeconomic Concepts",
     "Financial analysis performed using dollars or pesos of fixed purchasing power referenced to a specific base year, excluding inflation, uses:",
     ["A. Current (Actual) Pesos", "B. Constant (Real) Pesos", "C. Future Pesos", "D. Nominal Pesos"],
     "B", "Monetary units that reflect constant purchasing power, discounted using the real interest rate i_real.",
     "Current pesos represent actual cash outlays at the time they occur, discounted using the market nominal rate d.",
     "Never mix constant dollars with nominal interest rates, or current dollars with real interest rates!"),

    (87, "Corporate Income Tax & Tax Shield", "Taxation & Finance",
     "The cash tax savings generated for a profitable corporation because depreciation is an allowable tax-deductible expense is the:",
     ["A. Depreciation Tax Shield", "B. Tax Credit", "C. Excise Rebate", "D. Capital Gains Exemption"],
     "A", "Cash tax savings = Depreciation Expense × Corporate Tax Rate (d · T_c).",
     "Because depreciation shields income from taxation, accelerating depreciation (DDBM, SOYD) accelerates cash inflows.",
     "The tax shield is only the tax savings portion (d · T_c), NOT the entire depreciation amount d."),

    (88, "After-Tax Cash Flow (ATCF)", "Taxation & Finance",
     "The net cash flow remaining with a business enterprise after deducting operating costs and corporate income taxes from gross revenue is the:",
     ["A. Before-Tax Cash Flow (BTCF)", "B. After-Tax Cash Flow (ATCF)", "C. Net Operating Income", "D. Gross Margin"],
     "B", "ATCF = (Revenue - Expenses)(1 - T_c) + (Depreciation · T_c).",
     "Engineering economic evaluations of private commercial corporations must be performed on an after-tax basis.",
     "Depreciation is added back to net income because it is a non-cash accounting deduction."),

    (89, "Replacement Analysis: Defender vs Challenger", "Replacement Analysis",
     "In equipment replacement analysis, the existing asset currently in service is designated as the _____________, while the proposed new replacement asset is the _____________:",
     ["A. Defender; Challenger", "B. Challenger; Defender", "C. Sunk Asset; Prime Asset", "D. Legacy Asset; Modern Asset"],
     "A", "Standard terminology: Defender = existing in-place asset; Challenger = candidate new replacement technology.",
     "The defender is valued at its current net realizable market value (investment value), completely ignoring past sunk costs.",
     "If the challenger's annualized economic cost is lower than the defender's cost for the coming year, replace immediately."),

    (90, "Economic Service Life (ESL)", "Replacement Analysis",
     "The operating life duration n that minimizes an asset's Equivalent Uniform Annual Cost (EUAC) by balancing declining capital recovery with rising O&M cost is its:",
     ["A. Accounting Life", "B. Economic Service Life (ESL)", "C. Physical Life", "D. Tax Life"],
     "B", "The service period that yields the lowest Equivalent Uniform Annual Cost (EUAC).",
     "Physical life is how long equipment physically runs before breaking down; Economic life is how long it is financially optimal to keep it.",
     "An asset should be replaced when its economic service life has expired, even if it can physically operate for many more years."),

    (91, "Common Stock vs Preferred Stock", "Corporate Finance",
     "Corporate equity shares that pay a fixed contractual dividend and have liquidation priority over common shares, but typically carry no voting rights, are:",
     ["A. Common Stock", "B. Preferred Stock", "C. Treasury Stock", "D. Convertible Debentures"],
     "B", "A hybrid equity security with preferred claim on dividends and assets over common equity.",
     "Common stockholders hold residual claims, voting rights for board of directors, and unlimited upside potential.",
     "Preferred dividends are not tax-deductible for the issuing corporation, unlike bond interest."),

    (92, "Weighted Average Cost of Capital (WACC)", "Corporate Finance",
     "The overall composite hurdle rate of return a corporation must earn to satisfy its debt lenders and equity shareholders proportionally is the:",
     ["A. Marginal Cost", "B. Weighted Average Cost of Capital (WACC)", "C. Return on Equity", "D. Internal Rate"],
     "B", "WACC = (Weight of Debt · Cost of Debt After-Tax) + (Weight of Equity · Cost of Equity).",
     "Serves as the benchmark corporate hurdle rate (MARR) for major capital expenditures.",
     "Debt is cheaper than equity because interest payments are tax-deductible: After-tax cost of debt = r_d(1 - T_c)."),

    (93, "Equity Financing vs Debt Financing", "Corporate Finance",
     "Raising capital by issuing ownership shares of stock rather than borrowing funds through bank loans or bond issuances is:",
     ["A. Debt Financing", "B. Equity Financing", "C. Leveraged Buyout", "D. Mezzanine Debt"],
     "B", "Financing a business through shareholder equity investment without creating mandatory fixed debt obligations.",
     "Equity carries no legal obligation to pay dividends during unprofitable years, but dilutes ownership.",
     "Debt financing creates mandatory interest obligations and default risk, but does not dilute existing ownership."),

    (94, "Financial Leverage", "Corporate Finance",
     "The use of fixed-cost debt financing to amplify potential returns (and risks) to common equity shareholders is known as:",
     ["A. Operating Leverage", "B. Financial Leverage (Gearing)", "C. Capital Rationing", "D. Liquidity Coverage"],
     "B", "Employing borrowed capital to purchase assets, expecting earnings to exceed interest cost.",
     "If an engineering plant earns 15% on assets while debt cost is only 7%, equity return is heavily magnified.",
     "Financial leverage works both ways: if asset returns drop below debt cost, losses to equity holders are amplified."),

    (95, "Risk vs Uncertainty", "Decision Theory",
     "In engineering decision analysis, a condition where future outcomes are unknown but their probability distributions are mathematically known is:",
     ["A. Uncertainty", "B. Risk", "C. Determinism", "D. Ambiguity"],
     "B", "A situation where outcomes are not certain, but probabilities can be assigned (e.g. from historical data).",
     "Under pure uncertainty, probabilities of outcomes cannot be assigned or estimated.",
     "Expected Monetary Value (EMV) analysis calculates the probability-weighted payoff under risk conditions."),

    (96, "Expected Monetary Value (EMV)", "Decision Theory",
     "The sum of the products of each possible monetary outcome multiplied by its respective probability of occurrence is the:",
     ["A. Standard Deviation", "B. Expected Monetary Value (EMV)", "C. Opportunity Loss", "D. Risk Premium"],
     "B", "EMV = Σ (Probability_i · Payoff_i). The long-run average outcome if a decision is repeated many times.",
     "Decision tree analysis uses EMV to determine the optimal decision branch at chance nodes.",
     "Risk-neutral decision makers select the alternative that maximizes Expected Monetary Value."),

    (97, "Goodwill", "Accounting & Valuation",
     "An intangible accounting asset recognized when an enterprise is purchased for a price in excess of the fair market value of its net identifiable physical assets is:",
     ["A. Goodwill", "B. Copyright", "C. Franchise Value", "D. Patent"],
     "A", "The excess purchase price reflecting established reputation, customer loyalty, brand recognition, and engineering talent.",
     "Goodwill is recorded only in an actual acquisition transaction; companies cannot record internally generated goodwill.",
     "Goodwill is tested periodically for impairment rather than amortized on a straight-line basis."),

    (98, "Valuation: Going-Concern Value", "Business Valuation",
     "The overall valuation of an active engineering enterprise as an ongoing operational business capable of generating profits, rather than as liquidated assets, is its:",
     ["A. Liquidation Value", "B. Going-Concern Value", "C. Salvage Value", "D. Book Value"],
     "B", "The value of a firm as an operating entity with assembled workforce, plant, contracts, and revenue streams.",
     "Going-concern value is typically significantly higher than the piecemeal liquidation value of its physical assets.",
     "Liquidation value assumes a forced, immediate sale of physical machinery and scrap."),

    (99, "Law of Supply", "Market Mechanisms",
     "According to the basic economic Law of Supply, what happens to the quantity of a product that manufacturers are willing to supply as the market price increases?",
     ["A. Quantity supplied increases directly", "B. Quantity supplied decreases inversely", "C. Quantity supplied falls to zero", "D. Quantity supplied is independent of price"],
     "A", "Producers are willing to produce and sell more of a commodity as its market price rises, reflecting the profit incentive.",
     "The market supply curve slopes upward to the right.",
     "Higher prices allow producers to cover the higher marginal costs of less efficient production facilities."),

    (100, "Code of Ethics in Engineering Economics", "Professional Practice",
     "Under professional engineering licensure regulations in the Philippines (PRC), an engineer preparing project feasibility and cost estimates must:",
     ["A. Falsify cost estimates to ensure project funding approval", "B. Provide objective, truthful, and unbiased economic evaluations based on competent engineering standards", "C. Omit operating and maintenance costs to make proposals look more attractive", "D. Prioritize personal commercial interests above public safety and economic truth"],
     "B", "Engineers are bound by ethics to maintain absolute integrity, honesty, and objective truth in financial and technical feasibility studies.",
     "Deliberately understating project costs or overstating benefits breaches the Engineer's Code of Ethics and board licensure rules.",
     "Public safety and ethical stewardship of capital are paramount obligations under the Philippine Electrical Engineering Law.")
]

print(f"Loaded {len(terms)} term questions")

# Build TypeScript code for econTermsQuestions.ts
ts_code = "import { EconTermQuestion } from '../types';\n\n"
ts_code += "export const ECON_TERMS_QUESTIONS: EconTermQuestion[] = [\n"

for t in terms:
    num, term, cat, q, choices, ans, definition, exp, trap = t
    item = {
        "id": f"term-econ-{num:02d}",
        "termNumber": num,
        "category": cat,
        "termOrConcept": term,
        "prcExamRef": "PRC Board Exam Standard Terms",
        "difficulty": "Board Exam Standard" if num > 40 else "Foundation",
        "question": q,
        "choices": choices,
        "correctLetter": ans,
        "correctDefinition": definition,
        "examExplanation": exp,
        "boardExamTrapOrNote": trap
    }
    ts_code += "  " + json.dumps(item, indent=2).replace("\n", "\n  ") + ",\n"

ts_code = ts_code.rstrip(",\n") + "\n];\n"

with open("src/data/econTermsQuestions.ts", "w", encoding="utf-8") as f:
    f.write(ts_code)

print("Successfully written 100 terms questions to src/data/econTermsQuestions.ts!")
